### ISSUE TITLE
knock knock

### ISSUE THREAD

**Issue by astrojetson8** [lucavb/homebridge-mi-flora#1]
Hi, are you going to make this plugin available for rest of us?

**Comment by lucavb** [comment]
Quite frankly wasn't exactly going to. But I could get to that in the next couple of days

**Comment by astrojetson8** [comment]
@lucavb that would be great!

**Comment by astrojetson8** [comment]
@lucavb how did you go with this? is it still something you looking to share? thanks

**Comment by acc-ua** [comment]
that would be great if you share a complete version of the plugin.
thanks

**Comment by lucavb** [comment]
remind me again, what was missing with this plugin?

**Comment by acc-ua** [comment]
looks like there is no any config

**Comment by lucavb** [comment]
after a quick glance you need to specify 3 parameters:
name: the name obviously
deviceId: which I presume to be the MAC address of the device. not quite sure though, why I didn't name it MAC than. Maybe because the MiFlora plugin that I used didn't do so either. the source code of that plugin doesn't tell me much either :/
interval: time in seconds on how often you want this to be refreshed. I would suggest something along 300s because this drains the sensor obviously quicker.

**Comment by acc-ua** [comment]
hmm... could you please provide a sample? it will be much easier :)

**Comment by greenway12** [comment]
How does this plugin work? Can you please share config file please? @lucavb

**Comment by astrojetson8** [comment]
@lucavb  How do I use this plugin or are we still waiting this to be done?

**Comment by lucavb** [comment]
Hey,

sorry I haven't exactly been really active on GitHub as of late. Might I suggest you check out the code by @acc-ua  over at his fork of this project? He included a sample config and also appeared to have fixed a bug?

https://github.com/acc-ua/homebridge-mi-flora

**Comment by choibyeoli** [comment]
How I install this plugin in homebridge?

**Comment by lucavb** [comment]
So I finally finished writing about a somewhat decent README on this project. I hope it isn’t too late and I apologize for the long wait. 

If you have any questions feel free to ask.

**Comment by Nastras** [comment]
Thanks for your work👍

Can you explain a bit more about the installation process?

**Comment by Nastras** [comment]
sudo npm i homebridge-mi-flora -g is not working 🙁

**Comment by lucavb** [comment]
Yes npm won’t work with this project. Please read the installation of other plugins section of the README file.

**Comment by orilpik** [comment]
Hi @lucavb , I just recently installed the plugin but something is wrong when I run homebridge, because log says that The requested accessory '" + name '" was not registered by any plugin, but I checked that the plugin is running ok and the config.json is ok, with the MAC that Mi pi3 has discovered. Any thoughs on this? Thank you very much

**Comment by Nastras** [comment]
Hey,
i recommend you to use this version. This one is at npm and supports elgato eve history.

https://github.com/honkmaster/homebridge-mi-flower-care

**Comment by orilpik** [comment]
Thanks @Nastras but I came here because none of the two works for me :( I don't know where I'm wrong. 

All other accessories and platforms that I have work well and the json file is ok of sintasix, but when I rerun sudo homebridge it appears the error. Well, I'll keep trying

**Comment by lucavb** [comment]
hey, first of all I would recommend using the other recommended plugin. @honkmaster has definitely upgraded the plugin, plus he published it on npmjs so it can be easily installed.

In case of my plugin have you made sure, that your home bridge installation is configured to run with custom plugins? Because if it doesn't recognise this plugin, than it most likely didn't find it or was not configured to look for any.

**Comment by orilpik** [comment]
@lucavb thank you for your response! I have tried to install the plugin from @honkmaster via npm, and when I run homebridge the error appears. I have other plugins, but one thing is true, and is that all of them were installed via npm. I think that the sintax in accessories is correct but I don't know what I'm doing wrong. I'll keep trying things!

**Comment by honkmaster** [comment]
@orilpik Please check if you have all dependencies installed using apt-get, e.g, bluez. This is the most common mistake.

**Comment by orilpik** [comment]
Hi @honkmaster , thanks for your time. I just copy and paste what you explain in the Readme. If I paste it another time it says that every dependency is up to date. I don’t know where I’m wrong, It think it is something with the plugin installation process. I’ll keep trying and if I can’t make it work I’ll reinstall homebridge.

**Comment by orilpik** [comment]
![82ece4ac-64fd-4053-aa0d-17a2632416c8](https://user-images.githubusercontent.com/37545938/37687559-4d44c67c-2c9c-11e8-8118-9071fa985c4a.png)
![55af6a23-8379-4a29-9037-9e4d29fb891b](https://user-images.githubusercontent.com/37545938/37687560-4d6a0824-2c9c-11e8-8f83-c8a5747474be.png)
I put here my configjson file and the error that outuots when I run sudo homebridge If anyone can help! Thank you very much

**Comment by honkmaster** [comment]
There must be a missing dependency, otherwise I can't explain this behavior.

**Comment by lucavb** [comment]
I suggest moving this conversation to the other project by @honkmaster . You are obviously using his plugin.
